[package]
name = "mlc_builder"
version.workspace = true
edition.workspace = true

[dependencies]
mlc_core.workspace = true
mlc_syntax.workspace = true
llvm-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
rmp-serde = "1.3.1"
blake3.workspace = true
taskflowrs.workspace = true
tempfile.workspace = true
