//! Source-facing token names; Debug remains available for internal diagnostics.
use super::Token;

impl std::fmt::Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Union => "union",
            Self::AttributeStart => "#[",
            Self::AttributeEnd => "]#",
            Self::Pipe => "|>",
            Self::ColonColon => "::",
            Self::Equal => "==",
            Self::NotEqual => "!=",
            Self::RAngle => ">",
            Self::LAngle => "<",
            Self::GreaterOrEqual => ">=",
            Self::LessOrEqual => "<=",
            Self::LogicalAnd => "&&",
            Self::LogicalOr => "||",
            Self::Shl => "<<",
            Self::Shr => ">>",
            Self::FatArrow => "=>",
            Self::LParen => "(",
            Self::RParen => ")",
            Self::LBrace => "{",
            Self::RBrace => "}",
            Self::Semicolon => ";",
            Self::Assign => "=",
            Self::AddressOf => "@",
            Self::Dereference => "$",
            Self::LeftBracket => "[",
            Self::RightBracket => "]",
            Self::Arrow => "->",
            Self::Dot => ".",
            Self::Comma => ",",
            Self::Colon => ":",
            Self::LogicalNot => "!",
            Self::Plus => "+",
            Self::Minus => "-",
            Self::Multi => "*",
            Self::Div => "/",
            Self::Mod => "%",
            Self::BitAnd => "&",
            Self::BitOr => "|",
            Self::BitXor => "^",
            Self::BitNot => "~",
            Self::Function => "func",
            Self::Variable => "var",
            Self::Value => "val",
            Self::Constant => "const",
            Self::Mut => "mut",
            Self::Resource => "res",
            Self::Unit => "unit",
            Self::Using => "using",
            Self::Generic => "generic",
            Self::Enum => "enum",
            Self::VarList => "...",
            Self::Import => "import",
            Self::Export => "export",
            Self::Public => "pub",
            Self::Global => "global",
            Self::Api => "api",
            Self::In => "in",
            Self::True => "true",
            Self::False => "false",
            Self::If => "if",
            Self::Else => "else",
            Self::While => "while",
            Self::For => "for",
            Self::Break => "break",
            Self::Continue => "continue",
            Self::Match => "match",
            Self::Return => "return",
            Self::Null => "null",
            Self::Anonymous => "anonymous",
            Self::Default => "_",
            Self::Ident => "identifier",
            Self::IntLiteral => "integer literal",
            Self::FloatLiteral => "floating-point literal",
            Self::StringLiteral => "string literal",
            Self::SingleLineComment | Self::MultiLineComment => "comment",
        })
    }
}
